window.YTD.tweet.part0 = [ {
  "coordinates" : null,
  "retweeted" : false,
  "source" : "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
  "entities" : {
    "hashtags" : [ ],
    "symbols" : [ ],
    "user_mentions" : [ ],
    "urls" : [ ]
  },
  "display_text_range" : [ "0.0", "9.0" ],
  "favorite_count" : "0.0",
  "in_reply_to_status_id_str" : null,
  "geo" : null,
  "id_str" : "1020838720331804675",
  "in_reply_to_user_id" : null,
  "truncated" : false,
  "retweet_count" : "0.0",
  "id" : "1.02083872033180467E18",
  "in_reply_to_status_id" : null,
  "created_at" : "Sun Jul 22 01:11:31 +0000 2018",
  "place" : null,
  "favorited" : false,
  "full_text" : "It works!",
  "lang" : "en",
  "contributors" : null,
  "in_reply_to_screen_name" : null,
  "in_reply_to_user_id_str" : null
}, {
  "coordinates" : null,
  "retweeted" : false,
  "source" : "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client</a>",
  "entities" : {
    "hashtags" : [ ],
    "symbols" : [ ],
    "user_mentions" : [ ],
    "urls" : [ ]
  },
  "display_text_range" : [ "0.0", "7.0" ],
  "favorite_count" : "0.0",
  "in_reply_to_status_id_str" : null,
  "geo" : null,
  "id_str" : "999087078913724416",
  "in_reply_to_user_id" : null,
  "truncated" : false,
  "retweet_count" : "0.0",
  "id" : "9.9908707891372442E17",
  "in_reply_to_status_id" : null,
  "created_at" : "Wed May 23 00:38:16 +0000 2018",
  "place" : null,
  "favorited" : false,
  "full_text" : "wow :-)",
  "lang" : "und",
  "contributors" : null,
  "in_reply_to_screen_name" : null,
  "in_reply_to_user_id_str" : null
} ]
